-- V17__import_data_provinces.sql
-- Insert data for provinces table with actual province information

INSERT INTO provinces (id, code, name, type) VALUES
                                                 ('1', '91', 'An Giang', 'PROVINCE'),
                                                 ('2', '711', 'Bà Rịa - Vũng Tàu', 'PROVINCE'),
                                                 ('3', '95', 'Bạc Liêu', 'PROVINCE'),
                                                 ('4', '24', 'Bắc Giang', 'PROVINCE'),
                                                 ('5', '06', 'Bắc Kạn', 'PROVINCE'),
                                                 ('6', '27', 'Bắc Ninh', 'PROVINCE'),
                                                 ('7', '83', 'Bến Tre', 'PROVINCE'),
                                                 ('8', '52', 'Bình Định', 'PROVINCE'),
                                                 ('9', '707', 'Bình Dương', 'PROVINCE'),
                                                 ('10', '705', 'Bình Phước', 'PROVINCE'),
                                                 ('11', '601', 'Bình Thuận', 'PROVINCE'),
                                                 ('12', '96', 'Cà Mau', 'PROVINCE'),
                                                 ('13', '92', 'Cần Thơ', 'CITY'),
                                                 ('14', '04', 'Cao Bằng', 'PROVINCE'),
                                                 ('15', '48', 'Đà Nẵng', 'CITY'),
                                                 ('16', '66', 'Đắk Lắk', 'PROVINCE'),
                                                 ('17', '67', 'Đắk Nông', 'PROVINCE'),
                                                 ('18', '11', 'Điện Biên', 'PROVINCE'),
                                                 ('19', '713', 'Đồng Nai', 'PROVINCE'),
                                                 ('20', '87', 'Đồng Tháp', 'PROVINCE'),
                                                 ('21', '64', 'Gia Lai', 'PROVINCE'),
                                                 ('22', '02', 'Hà Giang', 'PROVINCE'),
                                                 ('23', '35', 'Hà Nam', 'PROVINCE'),
                                                 ('24', '01', 'Hà Nội', 'CITY'),
                                                 ('25', '42', 'Hà Tĩnh', 'PROVINCE'),
                                                 ('26', '30', 'Hải Dương', 'PROVINCE'),
                                                 ('27', '31', 'Hải Phòng', 'CITY'),
                                                 ('28', '93', 'Hậu Giang', 'PROVINCE'),
                                                 ('29', '79', 'Hồ Chí Minh', 'CITY'),
                                                 ('30', '33', 'Hưng Yên', 'PROVINCE'),
                                                 ('31', '56', 'Khánh Hòa', 'PROVINCE'),
                                                 ('32', '91', 'Kiên Giang', 'PROVINCE'),
                                                 ('33', '62', 'Kon Tum', 'PROVINCE'),
                                                 ('34', '12', 'Lai Châu', 'PROVINCE');