INSERT INTO provinces (id, code, name, type) VALUES
                                                 ('1', '91', 'An Giang', 'PROVINCE'),
                                                 ('2', '24', 'Bắc Ninh', 'PROVINCE'),
                                                 ('3', '04', 'Cao Bằng', 'PROVINCE'),
                                                 ('4', '96', 'Cà Mau', 'PROVINCE'),
                                                 ('5', '92', 'Cần Thơ', 'CITY'),
                                                 ('6', '48', 'Đà Nẵng', 'CITY'),
                                                 ('7', '66', 'Đắk Lắk', 'PROVINCE'),
                                                 ('8', '11', 'Điện Biên', 'PROVINCE'),
                                                 ('9', '75', 'Đồng Nai', 'PROVINCE'),
                                                 ('10', '82', 'Đồng Tháp', 'PROVINCE'),
                                                 ('11', '52', 'Gia Lai', 'PROVINCE'),
                                                 ('12', '01', 'Hà Nội', 'CITY'),
                                                 ('13', '42', 'Hà Tĩnh', 'PROVINCE'),
                                                 ('14', '31', 'Hải Phòng', 'CITY'),
                                                 ('15', '46', 'Huế', 'CITY'),
                                                 ('16', '33', 'Hưng Yên', 'PROVINCE'),
                                                 ('17', '56', 'Khánh Hòa', 'PROVINCE'),
                                                 ('18', '12', 'Lai Châu', 'PROVINCE'),
                                                 ('19', '15', 'Lào Cai', 'PROVINCE'),
                                                 ('20', '20', 'Lạng Sơn', 'PROVINCE'),
                                                 ('21', '68', 'Lâm Đồng', 'PROVINCE'),
                                                 ('22', '40', 'Nghệ An', 'PROVINCE'),
                                                 ('23', '37', 'Ninh Bình', 'PROVINCE'),
                                                 ('24', '25', 'Phú Thọ', 'PROVINCE'),
                                                 ('25', '51', 'Quảng Ngãi', 'PROVINCE'),
                                                 ('26', '22', 'Quảng Ninh', 'PROVINCE'),
                                                 ('27', '44', 'Quảng Trị', 'PROVINCE'),
                                                 ('28', '14', 'Sơn La', 'PROVINCE'),
                                                 ('29', '80', 'Tây Ninh', 'PROVINCE'),
                                                 ('30', '38', 'Thanh Hóa', 'PROVINCE'),
                                                 ('31', '19', 'Thái Nguyên', 'PROVINCE'),
                                                 ('32', '79', 'TP. Hồ Chí Minh', 'CITY'),
                                                 ('33', '08', 'Tuyên Quang', 'PROVINCE'),
                                                 ('34', '86', 'Vĩnh Long', 'PROVINCE');